In [1]:
from credentials import EIA_API_Key
import requests
import json
import pandas as pd
import time
import os

In [2]:
API = EIA_API_Key
URL = "https://api.eia.gov/v2/international/data/"

def get_eia_product(pid):
    rows = []
    offset = 0

    while True:
        params = {
            "api_key": API,
            "frequency": "annual",
            "data[0]": "value",
            "start": "2000",
            "end": "2025",
            "facets[productId][]": pid ,
            "sort[0][column]": "period",
            "sort[0][direction]": "desc",
            "offset": offset,
            "length": 5000
        }

        res = requests.get(URL, params=params).json()
        data = res["response"]["data"]

        rows.extend(data)

        if len(data) < 5000:
            break

        offset += 5000

    return pd.DataFrame(rows)

In [3]:
df_list = []
PRODUCT_IDS = [44,29] # lista de productId-uri

for pid in PRODUCT_IDS:
    df_list.append(get_eia_product(pid))

df = pd.concat(df_list, ignore_index=True)

In [4]:
eu_countries_iso3 = [
    "AUT",  # Austria
    "BEL",  # Belgium
    "BGR",  # Bulgaria
    "HRV",  # Croatia
    "CYP",  # Cyprus
    "CZE",  # Czech Republic
    "DNK",  # Denmark
    "EST",  # Estonia
    "FIN",  # Finland
    "FRA",  # France
    "DEU",  # Germany
    "GRC",  # Greece
    "HUN",  # Hungary
    "IRL",  # Ireland
    "ITA",  # Italy
    "LVA",  # Latvia
    "LTU",  # Lithuania
    "LUX",  # Luxembourg
    "MLT",  # Malta
    "NLD",  # Netherlands
    "POL",  # Poland
    "PRT",  # Portugal
    "ROU",  # Romania
    "SVK",  # Slovakia
    "SVN",  # Slovenia
    "ESP",  # Spain
    "SWE"   # Sweden
]

df_eu = df[df["countryRegionId"].isin(eu_countries_iso3)].copy()
df_eu.head()

,period,productId,productName,activityId,activityName,countryRegionId,countryRegionName,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unitName,value,unit
33,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,million metric tons of oil equivalent,7.10688109763967209533790268920011199378,MTOE
34,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,quadrillion Btu,.282023835219977057286209774346168941857,QBTU
35,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,terajoules,297550.897927175279431940636840975075981,TJ
42,2023,44,Primary energy,1,Production,BEL,Belgium,c,Country,None,None,million metric tons of oil equivalent,11.7061809334744304478466416587767595932,MTOE
43,2023,44,Primary energy,1,Production,BEL,Belgium,c,Country,None,None,quadrillion Btu,.46453880362989242695422331563651817116,QBTU

In [5]:
print(df_eu.shape)
df_eu.head()

(6831, 14)

,period,productId,productName,activityId,activityName,countryRegionId,countryRegionName,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unitName,value,unit
33,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,million metric tons of oil equivalent,7.10688109763967209533790268920011199378,MTOE
34,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,quadrillion Btu,.282023835219977057286209774346168941857,QBTU
35,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,terajoules,297550.897927175279431940636840975075981,TJ
42,2023,44,Primary energy,1,Production,BEL,Belgium,c,Country,None,None,million metric tons of oil equivalent,11.7061809334744304478466416587767595932,MTOE
43,2023,44,Primary energy,1,Production,BEL,Belgium,c,Country,None,None,quadrillion Btu,.46453880362989242695422331563651817116,QBTU

In [6]:
df_eu.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6831 entries, 33 to 66644
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   period                 6831 non-null   object
 1   productId              6831 non-null   object
 2   productName            6831 non-null   object
 3   activityId             6831 non-null   object
 4   activityName           6831 non-null   object
 5   countryRegionId        6831 non-null   object
 6   countryRegionName      6831 non-null   object
 7   countryRegionTypeId    6831 non-null   object
 8   countryRegionTypeName  6831 non-null   object
 9   dataFlagId             226 non-null    object
 10  dataFlagDescription    226 non-null    object
 11  unitName               6831 non-null   object
 12  value                  6831 non-null   object
 13  unit                   6831 non-null   object
dtypes: object(14)
memory usage: 800.5+ KB

In [7]:
#Distribuția datelor
df_eu['activityName'].value_counts()

activityName
Generation     2484
Production     1863
Consumption    1863
Capacity        621
Name: count, dtype: int64

In [8]:
# group by productName and get descriptive statistics for 'value'
df_eu.groupby("productName")['value'].describe()

               count unique top freq
productName
Primary energy  3726   3685   0   36
Renewables      3105   3021   0   55

In [9]:
len(df_eu.countryRegionName.unique())

27

In [10]:
# anii unici disponibili
df_eu.period.unique()

array(['2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016',
       '2015', '2014', '2013', '2012', '2011', '2010', '2009', '2008',
       '2007', '2006', '2005', '2004', '2003', '2002', '2001'],
      dtype=object)

In [11]:
# columnele disponibile
df_eu.columns

Index(['period', 'productId', 'productName', 'activityId', 'activityName',
       'countryRegionId', 'countryRegionName', 'countryRegionTypeId',
       'countryRegionTypeName', 'dataFlagId', 'dataFlagDescription',
       'unitName', 'value', 'unit'],
      dtype='object')

In [12]:
# product map: productId, productName, activityName
product_map = df_eu[['productId', 'productName',"activityName"]].drop_duplicates().sort_values('productId')
product_map

      productId     productName activityName
36863        29      Renewables     Capacity
37156        29      Renewables   Generation
33           44  Primary energy   Production
825          44  Primary energy  Consumption

In [13]:
product_map = df_eu[['productId', 'productName',"activityName","unitName"]].drop_duplicates().sort_values('productId')
product_map

,productId,productName,activityName,unitName
36863,29,Renewables,Capacity,million kilowatts
37156,29,Renewables,Generation,billion kilowatthours
37157,29,Renewables,Generation,million metric tons of oil equivalent
37158,29,Renewables,Generation,quadrillion Btu
37159,29,Renewables,Generation,terajoules
33,44,Primary energy,Production,million metric tons of oil equivalent
34,44,Primary energy,Production,quadrillion Btu
35,44,Primary energy,Production,terajoules
825,44,Primary energy,Consumption,million metric tons of oil equivalent
826,44,Primary energy,Consumption,quadrillion Btu
827,44,Primary energy,Consumption,terajoules

In [14]:
from dotenv import load_dotenv
from sqlalchemy import create_engine
import os

load_dotenv()
engine = create_engine(os.getenv("NEON_URL"))
print(engine)

Engine(postgresql://dsw_writer:***@ep-royal-scene-agnlimgp-pooler.c-2.eu-central-1.aws.neon.tech/neondb?channel_binding=require&sslmode=require)

In [15]:
df = pd.read_sql(
    'SELECT * FROM public."Team2_EIA_Raw_Data";',
    engine
)

df

,period,productId,productName,activityId,activityName,countryRegionId,countryRegionName,countryRegionTypeId,countryRegionTypeName,dataFlagId,dataFlagDescription,unitName,value,unit
0,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,million metric tons of oil equivalent,7.10688109763967209533790268920011199378,MTOE
1,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,quadrillion Btu,.282023835219977057286209774346168941857,QBTU
2,2023,44,Primary energy,1,Production,AUT,Austria,c,Country,None,None,terajoules,297550.897927175279431940636840975075981,TJ
3,2023,44,Primary energy,1,Production,BEL,Belgium,c,Country,None,None,million metric tons of oil equivalent,11.7061809334744304478466416587767595932,MTOE
4,2023,44,Primary energy,1,Production,BEL,Belgium,c,Country,None,None,quadrillion Btu,.46453880362989242695422331563651817116,QBTU
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6826,2001,29,Renewables,12,Generation,SVN,Slovenia,c,Country,None,None,terajoules,13726.7999999999922757931452764,TJ
6827,2001,29,Renewables,12,Generation,SWE,Sweden,c,Country,None,None,billion kilowatthours,82.774,BKWH
6828,2001,29,Renewables,12,Generation,SWE,Sweden,c,Country,None,None,million metric tons of oil equivalent,7.117282885941777028552453116,MTOE
6829,2001,29,Renewables,12,Generation,SWE,Sweden,c,Country,None,None,quadrillion Btu,.28243661154053210556,QBTU
6830,2001,29,Renewables,12,Generation,SWE,Sweden,c,Country,None,None,terajoules,297986.3999999998323200896425672,TJ

In [16]:
df_eu.to_sql(
    "Team2_EIA_Raw_Data",
    engine,
    if_exists="replace",
    index= False
)

831